"""empty message

Revision ID: 06a23193758c
Revises: 
Create Date: 2020-05-07 16:23:20.381218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a23193758c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orig_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pred_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ref_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
